[package]
name = "no_duplicates"
version = "0.1.0"
authors = ["Joshua Moody"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
